### ISSUE TITLE
The precompiled NIF file does not exist in the checksum file

### ISSUE THREAD

**Issue by thiagopromano** [avencera/fast_rss#19]
It seems that the checksums file on hex.pm is called checksum-Elixir.FastRss.Native.exs instead of checksum-Elixir.FastRSS.Native.exs, so upgrading gives this error:

```
== Compilation error in file lib/fast_rss.ex ==
** (RuntimeError) Error while downloading precompiled NIF: the precompiled NIF file does not exist in the checksum file. Please consider run: `mix rustler_precompiled.download FastRSS.Native --only-local` to generate the checksum file..

You can force the project to build from scratch with:

    config :rustler_precompiled, :force_build, fast_rss: true

In order to force the build, you also need to add Rustler as a dependency in your `mix.exs`:

    {:rustler, ">= 0.0.0", optional: true}

    lib/fast_rss.ex:13: (module)
    lib/fast_rss.ex:6: (module)
```

This was caused by #17. It seems that the RELEASE.md file has been updated but not the checksums filename.

Best regards,

Thiago Romano

**Comment by tmr08c** [comment]
Sorry about this not working, @thiagopromano  and @praveenperera 😿 

Are you seeing the debug log line that shows which NIF it's trying to fetch from the cache? This should come up just before the error you are seeing and look something like:

```
11:31:56.668 [debug] Copying NIF from cache and extracting to /path/to/project/_build/test/lib/fast_rss/priv/native/libfastrss-v0.4.3-nif-2.16-x86_64-apple-darwin.so
```

I'm hoping to learn about the OS/architecture combo you are using, and if it is included in the [buid targets](https://github.com/avencera/fast_rss/blob/9157f4536a968e25e7ec48c530b565e6f1771711/.github/workflows/release.yml#L32-L40).

If it's not asking too much, I'd also be curious if you could try adding [`explorer`](https://github.com/elixir-nx/explorer) to your project's dependency list and seeing if you run into similar issues. `explorer` is one of the projects I based #17 on, so that could possibly help me narrow down something I missed.

**Comment by tmr08c** [comment]
@praveenperera is it possible you had an existing checksum file on your filesystem when you [ran the new command](https://github.com/avencera/fast_rss/commit/9157f4536a968e25e7ec48c530b565e6f1771711)?

Locally I tried running `mix rustler_precompiled.download FastRss.Native --all --print` (the lowercase version) followed by `mix rustler_precompiled.download FastRSS.Native --all --print` (the proper-cased version) and, on my system, I still have a file named `checksum-Elixir.FastRss.Native.exs`. Only after removing the checksum file and re-running the command did I get the proper-case version.

I see you released [`v0.4.4`](https://github.com/avencera/fast_rss/releases/tag/v0.4.4), so maybe you've figured out the real issue?

**Comment by praveenperera** [comment]
Ya @tmr08c @thiagopromano I think its good now. I deleted the old file, created a new release and published a new version

**Comment by thiagopromano** [comment]
Yes, it worked, thanks everyone!
